<% def env(a, b); e = ENV["obtvse_#{a}"]; e ? e : b; end %>

title: <%= env :title,    'Laura Diane Hamilton' %>
domain: <%= env :domain,    'http://www.lauradhamilton.com' %>
name:    <%= env :name,    'Laura Diane Hamilton' %>
twitter: <%= env :twitter, 'lauradhamilton' %>
linkedin: <%= env :linkedin, 'lauradhamilton' %>
github:  <%= env :github,  'lauradhamilton'  %>
googleplus: <%= env :googleplus, '110556329633561103408' %>
email:   <%= env :email,   'lauradhamilton@gmail.com'  %>
about:   <%= env :about,   'Technical Product Manager at Groupon<br><br><a href="/lauradhamilton_resume.pdf">Resumé</a>' %>

# Google Analytics
ga_id:   <%= env :ga, 'UA-38928252-1'  %>
